### ISSUE TITLE
Problema no parâmetro --config no server-cli

### ISSUE THREAD

**Issue by darcyjunior** [wppconnect-team/server-cli#105]
O server-cli ignora o parâmetro --config para adicionar o path para o arquivo config.json

https://github.com/wppconnect-team/server-cli/blob/main/src/program.js

**Comment by comercializze** [comment]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type boolean (true)
    at Object.openSync (node:fs:577:10)
    at Object.readFileSync (node:fs:453:35)
    at Object.run (/usr/local/lib/node_modules/@wppconnect/server-cli/dist/index.js:35:164)
    at Object.<anonymous> (/usr/local/lib/node_modules/@wppconnect/server-cli/bin/wppserver.js:20:8)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
